name: Create Databricks Solution

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Init
      working-directory: ./terraform/databricks_solution
      run: |
        terraform init -upgrade -backend-config=resource_group_name=base \
          -backend-config=storage_account_name=tkubicastore \
          -backend-config=container_name=tfstate \
          -backend-config=key=databricks_solution.tfstate \
          -backend-config=subscription_id="d3b7888f-c26e-4961-a976-ff9d5b31dfd3" \
          -backend-config=use_msi=true \
          -backend-config=client_id=${{ secrets.AZURE_CLIENT_ID }} \
          -backend-config=tenant_id=${{ secrets.AZURE_TENANT_ID }}


    - name: Terraform Apply
      working-directory: ./terraform/databricks_solution
      run: |
        retries=0
        max_retries=1
        until terraform apply -auto-approve || [ $retries -eq max_retries ]; do
          echo "Terraform apply failed, retrying in 5 seconds..."
          sleep 5
          retries=$((retries+1))
        done