name: Build and push Users Generator

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'datageneration/users/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log into registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push container
      uses: docker/build-push-action@v4
      with:
        context: datageneration/users
        push: true
        tags: ghcr.io/tkubica12/generate_users:latest
